Traceback (most recent call last):
  File "create_sim_dataset.py", line 73, in <module>
    main()
  File "create_sim_dataset.py", line 69, in main
    create_hdf5_dataset(lof_data_path, file_name)
NameError: name 'lof_data_path' is not defined
